### ISSUE TITLE
[NEW SECTION] document model specification for initial and unfished numbers at age

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/collaborative_workflow#104]
**Title of section**
Not a new section, just an expansion of the "Initial values" section: https://noaa-fims.github.io/collaborative_workflow/m1-model-specification.html#initial-values

**Suggested section content and location**
Include equations and/or description for the "unfished" and "initial" numbers and age and clarify the relationship between these two things. The population.hpp file includes https://github.com/NOAA-FIMS/FIMS/blob/180-feat-population/inst/include/population_dynamics/population/population.hpp both `CalculateInitialNumbersAA()` and `CalculateUnfishedNumbersAA()`. Is this just semantics and these aren't really two separate things?

**Additional context**
This came up during development of unit tests for the population module. @nathanvaughan-NOAA, I hear that you put some thought into this stuff during the development of the , so I'm initially assigning this to you.

**Comment by nathanvaughan-NOAA** [comment]
Thanks for pointing this out @iantaylor-NOAA . I have added some additional documentation to a new branch issue_104_initialNAA_unfishedNAA_documentation. This was my first time pushing changes to the collaborative workflow document so hopefully I knitted everything correctly. If this clears up the issue we can make a pull request to main.

**Comment by iantaylor-NOAA** [comment]
Thanks @nathanvaughan-NOAA!
The document knitted just fine and the results look good. I'm pasting the expanded sections below from the html of the github action. Unless someone has further input on this, I think you could create a pull request any time.
![image](https://user-images.githubusercontent.com/4992918/204926833-4156c0d0-d848-41bd-8bd3-39b84be89f2a.png)

**Comment by cmlegault** [comment]
Hi @nathanvaughan-NOAA and @iantaylor-NOAA ,

Thanks for writing up the unexploited and initial values sections. I have a few of minor/trivial questions.

1. I think there is a typo in the UnfishedNAA_{t,a} equation, M_{t-1} should be exp(-M_{t-1, a-1}, right?
2. Perhaps too in the weeds, but would it be helpful to show the plus group calculation explicitly for UnfishedNAA_{t,A}?
3. I'm a bit confused by R0_t? I was expecting something like R = f(SSB_{t-1}) with no recruitment deviations. Perhaps the current notation means the same thing?
4. Should we be using the R0 and steepness approach for the Bev-Holt SRR given Liz Brooks' talk at CAPAM? Would it be better to use the original alpha and beta approach then derive R0 and steepness if desired with explicitly defined weights at age, maturity at age, and natural mortality at age (the phi_F calculations)?

I know we can change everything later, just wanted to bring these questions up know to ensure we think about them early on before we get too stuck in our ways.

Thanks again for writing the documentation and making it easy to find.

Cheers,
Chris

**Comment by nathanvaughan-NOAA** [comment]
Thanks Chris for catching these issues

I think there is a typo in the UnfishedNAA_{t,a} equation, M_{t-1} should be exp(-M_{t-1, a-1}, right? Yes this is a typo I will correct it.


Perhaps too in the weeds, but would it be helpful to show the plus group calculation explicitly for UnfishedNAA_{t,A}?
I don't think we have any plus group calculation at the moment but I agree we need to add them for both fished and unfished NAA. 

I'm a bit confused by R0_t? I was expecting something like R = f(SSB_{t-1}) with no recruitment deviations. Perhaps the current notation means the same thing?
The logic here for R0 is to look at what would the unfished biomass (including no historic fishing mortality) be so this just uses the R0 not the previous SSB as that is effected by fishing. The SSB based equation with UnfishedSSB would just return R0.

Should we be using the R0 and steepness approach for the Bev-Holt SRR given Liz Brooks' talk at CAPAM? Would it be better to use the original alpha and beta approach then derive R0 and steepness if desired with explicitly defined weights at age, maturity at age, and natural mortality at age (the phi_F calculations)?
Liz is the expert so that sounds reasonable.

I know we can change everything later, just wanted to bring these questions up know to ensure we think about them early on before we get too stuck in our ways.
For now I think most of these issues are things that will be 100% refactored so I don't think we will get stuck with them. I totally agree though that we make sure not to get ourselves stuck with suboptimal decisions. 

Thanks again for writing the documentation and making it easy to find.

**Comment by iantaylor-NOAA** [comment]
@nathanvaughan-NOAA, I see a checked box in this issue: https://github.com/NOAA-FIMS/FIMS/issues/354 which indicates that a plus group calculation was fixed in the tests. Does that mean we can close this issue?

**Comment by nathanvaughan-NOAA** [comment]
Thanks @iantaylor-NOAA I think so. From what I remember it turned out that the plus group issues were just a misunderstanding rather than an actual error so I think we just have to make the pull request that I had forgotten about for 8 months :)
