### ISSUE TITLE
[NEW SECTION] add information on use of codespaces

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/collaborative_workflow#122]
**Title of section**
codespaces

**Suggested section content and location**
Within Chapter 6 Developer Software Guide, document use of codespaces.

This is related to https://github.com/NOAA-FIMS/collaborative_workflow/issues/87 and https://github.com/NOAA-FIMS/collaborative_workflow/issues/101 which are related to doxygen which need not be installed locally if the developer is using codespaces.

**Comment by k-doering-NOAA** [comment]
@Andrea-Havron-NOAA notes that using the Rstudio option should be documented  (e.g., how to start rserver, which terminal to use, and other details)

**Comment by k-doering-NOAA** [comment]
@Huihualee-NOAA and I tried out the rstudio option in codespaces today. Two unexpected things we found are worth noting:
1. Committing from Rstudio is not an option, commits had to be done in VScode
2. Because we were working on Rstudio on a port (a separate browser tab from the codespace), our session timed out after 30 minutes, because we weren't working directly on vscode. We figured this out when it would Rstudio wouldn't save our changes automatically, and we ended up having to copy/paste our file after restarting the codespace and rstudio session to make sure the changes were preserved. It is possible to [reset the timeout](https://docs.github.com/en/codespaces/setting-your-user-preferences/setting-your-timeout-period-for-github-codespaces#about-the-idle-timeout) in your personal settings, so maybe a longer time out is better for those who plan to work in rstudio (The downside is it will use more of your codespace minutes)
