### ISSUE TITLE
Documentation required of new features

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/collaborative_workflow#4]
## Problem

What documentation will be required of new features because stand-a-lone documentation that doesn't go into detail about how a feature fits into the bigger picture might not be enough. See #1 for @cmlegault comment that started this thought.

## Proposed solution

Require new features be added to an existing vignette before pull request is merged.

## Potential problems

* Hard to remember that it is a requirement because it is not standard practice.
* Vignettes might not exist yet.

**Comment by ChristineStawitz-NOAA** [comment]
I added in a couple of sections of documentation here - struggled with the content because I don't want to duplicate too much of the blog post I link to in the first section.

What do you think about the sections? I will update the content w/in the sections when I don't have kids home and can think more clearly
https://noaa-fims.github.io/collaborative_workflow/documentation-template.html

**Comment by ChristineStawitz-NOAA** [comment]
I have added a suggestion that the developer check the [software user guide](https://noaa-fims.github.io/collaborative_workflow/software-user-guide.html) page which can serve as a getting started vignette for now.
